# Generated by Django 6.0.1 on 2026-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social_user',
            field=models.BooleanField(default=False, verbose_name='Через соцсети'),
        ),
    ]
