# Generated by Django 6.0.1 on 2026-02-26 10:53

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='products/%Y/%m/'),
        ),
    ]
